# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: "jekyll/minima@c6e74bb" # c6e74bb is release v2.5.2 from sept24
# remote_theme: "jekyll/minima@1e8a445" # advised in readme
remote_theme: "jekyll/minima" # should be v3


title: "" #repied.github.io # github pages makes it 'repied' if not defined here
description: "" # Will appear at the bottom of each page
show_downloads: false

#author:
#  name: repied

minima:
  skin: auto
  hide_site_feed_link: true
  # nav_pages: # Not I removed the nav from the theme in header.html
  #   - about.md
  #   - petrole.md

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme 
  - jekyll-seo-tag

exclude: 
  - .vscode
  - .devcontainer
  - .gitignore
  - .venv
  - .python-version
  - uv.clock 
  - pyproject.toml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md


google_analytics: G-W2YD6XQDM5

# <!-- Google tag (gtag.js) -->
# <script async src="https://www.googletagmanager.com/gtag/js?id=G-W2YD6XQDM5"></script>
# <script>
#   window.dataLayer = window.dataLayer || [];
#   function gtag(){dataLayer.push(arguments);}
#   gtag('js', new Date());

#   gtag('config', 'G-W2YD6XQDM5');
# </script>

# config examples from minima
# Site-wide settings
# ------------------
#
# title: Your awesome title
#
# author:
#   name: GitHub User
#   email: your-email@domain.com
#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
# description: >
#   Write an awesome description for your new site here. You can edit this line
#   in _config.yml. It will appear in your document head meta (for Google search
#   results) and in your feed.xml site description.


# Build settings
# --------------
#
# If you wish to use the gem-version of Minima with or without a Gemfile, use
#   the following setting:
# theme: minima
#
# **OR** if you wish to use the theme directly from the GitHub repository by
#   bypassing a Gemfile, use the following setting instead.
#   It is best that you lock to a particular commit and update if uptream changes
#   do not affect your site adversely.
# remote_theme: jekyll/minima@d4d779a
#
# Minima requires the following plugins:
# plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
#
# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]


# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
#
#  *All described config keys below should be nested under the top-level
#   `minima` key.*
#
# minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
#   skin: auto
#
#   Specific pages for site navigation.
#     If you wish to link only specific pages in the site-navigation, use this
#     and list the `path` property (as represented via Liquid) of the pages in
#     the order they should be rendered.
#   nav_pages:
#     - about.md
#
#   Set to `true` to show excerpts on the homepage.
#   show_excerpts: false
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
#   date_format: "%b-%d-%Y"
#
#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
#   social_links:
#     - title: Minima Theme repository at GitHub
#       icon: github
#       url: "https://github.com/jekyll/minima"
#     - title: Jekyll at X (formerly Twitter)
#       icon: x-twitter
#       url: "https://x.com/jekyllrb"
#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.
#   hide_site_feed_link: false
